### ISSUE TITLE
Worksheet constructor

### ISSUE THREAD

**Issue by HLWeil** [Freymaurer/Fable.Openpyxl#4]
```fsharp
    type WorksheetStatic =
        [<Emit("new $0(parent=$1, title=$2)")>]
        abstract member create: parent:Workbook * title:string -> Worksheet

    [<Import("Worksheet", "openpyxl.worksheet.worksheet")>]
    let Worksheet : WorksheetStatic = nativeOnly
```

**Comment by Freymaurer** [comment]
I think adding this function is against best practise (at least from the point of view of the openpyxl developers:

![image](https://github.com/Freymaurer/Fable.Openpyxl/assets/39732517/63258102-ab1f-4962-aaab-8fe69ad4d700)

As you must give the Worksheet.create function a parent workbook, i do not see any reason to add this function if it goes against the recommended usage. What do you think about this @HLWeil

**Comment by HLWeil** [comment]
Agreed!
